# Generated by Django 5.2.3 on 2025-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.IntegerField(default=70, help_text='Minimum score required to pass this exam (as a percentage or raw score).'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text_for_fill_in_blank',
            field=models.CharField(blank=True, help_text='For Fill-in-the-Blank questions, provide the correct answer text.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('FB', 'Fill-in-the-Blank')], default='MC', max_length=2),
        ),
    ]
