# Generated by Django 5.2.3 on 2025-07-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for fill-in-the-blank questions', null=True),
        ),
    ]
