# Generated by Django 5.2.3 on 2025-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('FB', 'Fill-in-the-Blank'), ('MS', 'Multiple Select')], default='MC', max_length=2),
        ),
    ]
