# Generated by Django 5.2.3 on 2025-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
