# Generated by Django 5.2.3 on 2025-07-22 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_studentanswer_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text_for_fill_in_blank',
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='question',
            name='score_points',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points awarded for a correct answer.', max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('student', 'exam')},
        ),
    ]
