# Generated by Django 5.2.3 on 2025-07-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_question_answer_text_for_fill_in_blank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
    ]
