# Generated by Django 5.2.3 on 2025-07-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_examattempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomize_choices',
            field=models.BooleanField(default=False, help_text='If true, answer choices will be randomized for each student.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='If true, questions will be randomly selected for each student attempt.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_questions_to_ask',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to ask from the total question pool. If blank, all questions will be asked.', null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='assigned_question_ids',
            field=models.JSONField(default=list, help_text='List of question IDs assigned to this student for this attempt'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level of the question for better randomization.', max_length=10),
        ),
    ]
