# Generated by Django 5.2.3 on 2025-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_randomize_choices_exam_randomize_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='pass_mark',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='passing_score',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
