# Generated by Django 5.2.3 on 2025-07-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_examattempt_pass_mark_examattempt_passing_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='pass_mark',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='passing_score',
        ),
    ]
